language: python
sudo: false
python:
- '2.7'

install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- |
  conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy=1.11 pandas pytest matplotlib
- source activate test-environment
- conda list
- pip install .
- pip install https://github.com/UDST/orca/archive/master.zip
- pip install urbansim
- git clone -b developer git@github.com:urbansim/urbansim_parcels.git
- pip install ./urbansim_parcels

script:
- py.test
- cd urbansim_parcels/sf_example; python simulate.py